---
# tasks file for roles/deploy_app

- name: Copy app archive
  copy:
    src: "{{ jenkins_workspace }}/artifacts/app.tar.gz"  # Use absolute path to Jenkins workspace
    dest: /opt/app.tar.gz
    mode: '0644'

- name: Copy hash
  copy:
    src: "{{ jenkins_workspace }}/artifacts/hash.txt"  # Use absolute path to Jenkins workspace
    dest: /opt/hash.txt
    mode: '0644'

- name: Verify SHA256 hash
  shell: |
    cd /opt
    sha256sum -c hash.txt
  register: hash_output
  failed_when: "'OK' not in hash_output.stdout"
  changed_when: false

- name: Extract app
  unarchive:
    src: /opt/app.tar.gz
    dest: /opt/
    remote_src: yes

- name: Install Python requirements
  pip:
    requirements: /opt/flaskapp/requirements.txt

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/secureflask.service
    content: |
      [Unit]
      Description=Secure Flask App
      After=network.target
      [Service]
      WorkingDirectory=/opt/flaskapp
      ExecStart=/usr/bin/python3 /opt/flaskapp/app.py
      Restart=always
      User=ubuntu
      [Install]
      WantedBy=multi-user.target

- name: Enable & start Flask
  systemd:
    name: secureflask
    state: started
    enabled: yes
