- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Install Certbot
  package:
    name: certbot
    state: present

- name: Deploy Nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Obtain SSL certificates using Certbot
  command: certbot --nginx -d 13.60.105.236--non-interactive --agree-tos -m talktoibinabo@gmail.com

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: true
